### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by dandv** [danishkhan/NicEdit#13]
I see on nicedit.com that the last release was in 2012.

There's also a bogus 1969 date.

**Comment by inspire22** [comment]
I'd suggest ckeditor or redactor at this point.

**Comment by dandv** [comment]
I've been [evaluating 40+ editors](https://github.com/iDoRecall/media/blob/master/Comparison-of-JavaScript-WYSIWYG-editors.md) over the weekend. Redactor can't paste images.

**Comment by danishkhan** [comment]
I moved NicEdit over to GitHub a few years ago because I was using it for a project and figured since it wasn't on GitHub I'd create a project for it. I have no use for it anymore, so I haven't really been maintaining it much.
