### ISSUE TITLE
I can't render the editor again after Ajax refresh

### ISSUE THREAD

**Issue by kvvaradha** [danishkhan/NicEdit#15]
i can't render the editor again after the ajax refesh. i need functional call to reload it after the ajax rendered form . i am trying to use it on the frontaccounting comments area. 
so please help me to get it work on

**Comment by inspire22** [comment]
Yes, it doesn't work ajax refresh.  This project hasn't been maintained for 3+ years.  Switch to ckeditor...

**Comment by danishkhan** [comment]
This project isn't maintained anymore. If you'd like to add a fix a PR is welcome otherwise you might want to fork it or look for another editor.

**Comment by kvvaradha** [comment]
Thank you for both of your responses. I am started using  TinyMCE Editor now.
