### ISSUE TITLE
stretch editor issue

### ISSUE THREAD

**Issue by ashishsinghyopmail** [danishkhan/NicEdit#16]
hello...

i am using NicEdit plugin to change all text area to editor on my form but i am not able to stretch from corner like text area.
can some one help to how to change or configure for stretchable editor box....
screenshot ....http://screencast.com/t/vf73GWsba
Thanks for help.....

**Comment by inspire22** [comment]
This project hasn't been maintained for 3+ years.  Switch to ckeditor...

**Comment by danishkhan** [comment]
Yeah, ckeditor is a good option to try out
