### ISSUE TITLE
nicEditor is not responsive

### ISSUE THREAD

**Issue by GC08** [danishkhan/NicEdit#18]
Size of nicEditor is fixed. Try to use css stylesheet (paddings, margins) instead of fixed size of element. Try to use classes and ids for elements.

**Comment by danishkhan** [comment]
@GC08 this project is no longer maintained. However, if you have a fix, Pull Requests are welcome.

**Comment by kavin-90** [comment]
after replacing 
`width:(parseInt(B.getStyle("width"))||B.clientWidth)+"px"` to `width: "100%"`
and
`var E={width:newX+"px"` to `var E={width:"100%",`

it become responsive 😄
