### ISSUE TITLE
Make Width measured in % rather than px

### ISSUE THREAD

**Issue by MrChriZ** [danishkhan/NicEdit#21]
I was trying to used NicEdit in a Tabbed Web Page.
The editor kept setting itself up as 100px wide.  To resolve this I changed all a number width px in the JS file to %.  This seemed to work really well.

I think it might be a good thing to do is the master copy.

**Comment by danishkhan** [comment]
@MrChriZ this isn't a maintained project anymore, but if you have a fix in mind please open a Pull Request
