### ISSUE TITLE
Multiple NicEdit with JQuery Dialog positions offset

### ISSUE THREAD

**Issue by MrChriZ** [danishkhan/NicEdit#22]
For Information only (I'm aware the project is no longer actively maintained).
I had a few problems where I had multiple NicEdit textareas within a JQuery Dialog.
The first problem is that when clicking on buttons like HTML the popup does not stay active
http://stackoverflow.com/questions/42541766/modal-jquery-ui-dialog-with-nicedit-issue

I concluded that this was because NicEdit attaches the EditHTML panel to the document body, rather than insert it into the same part of the DOM as the panel itself.  As such I believe the panel is not in the JQuery Dialog.

For my use case it was sufficient to just make the dialog non modal to work around this.

The second problem I believe stems from the same issue.  The NicEdit EditHTML Panels and their ilk would end up positioned wrongly where multiple NicEdit editors were on the dialog.  In some cases the panel would open some 600 pixels or so below my JQuery Dialog, so the user would have to scroll down to them.

The ideal fix would be to have the panel inside the JQuery Dialog and positioned relative to that - rather than the document body.  Alas that is quite beyond my Javascript skills - especially since NicEdit doesn't use JQuery.

As a hacky quick fix however that works for my uses I instead made the panel open at the coordinates of the mouse cursor.  To do this I placed the following at the top of NicEdit.js:
```
var cursorX;
var cursorY;
document.onmousemove = function (e) {
    cursorX = e.pageX;
    cursorY = e.pageY;
}

```

and then further down around line 1000:
```
var nicEditorPane = bkClass.extend({
    construct: function(D, C, B, A) {
        this.ne = C;
        this.elm = D;
        this.pos = D.pos();

        
        this.contain = new bkElement("div").setStyle({
            zIndex: "9999",
            overflow: "hidden",
            position: "absolute",
            left: cursorX + "px",
            top: cursorY + "px"
```

I don't feel something this hacky should be put in a pull request... but it may help someone.
Should someone have a better solution I would love to have it!

https://github.com/MrChriZ/NicEdit/blob/master/nicEdit.js

**Comment by tekrat** [comment]
I've branched this code and have a fix for this issue.  I haven't committed it back here yet because I want to do some more testing.  But so far it fixes the issue without being so 'hacky.'

https://github.com/tekrat/NicEdit/tree/master
