### ISSUE TITLE
link problem

### ISSUE THREAD

**Issue by puraminy** [danishkhan/NicEdit#7]
I'v heared this version has not link problem in ie8 and firefox but it still has the problem

I have a problem with nicEdit link creation in IE and Firefox.
-----------------------------------------

if(!this.ln) {
        var tmp = 'javascript:nicTemp();';
        this.ne.nicCommand("createlink",tmp);
        this.ln = this.findElm('A','href',tmp);
        // set the link text to the title or the url if there is no text selected
        alert(this.ln);
        if (this.ln.innerHTML == tmp) {
            this.ln.innerHTML = this.inputs['title'].value || url;
        };
    }
--------------------------------------------------------
the code above is called when no text is selected, Chrome returns 'javascript:nicTemp()' for the alert(this.ln) while IE 8 and Firefox returns 'undefined' so the next line after the alert get error in IE and Firefox.

it seems findElem can't find the newly created link by nicCommand which in turn calls execCommand

How can I solve this problem? how can I force the document to be updated ....

please help

**Comment by danishkhan** [comment]
This project isn't maintained anymore. If you'd like to add a fix a PR is welcome otherwise you might want to fork it or look for another editor.
