### ISSUE TITLE
Unordered List button appears selected on load when editor is inside <UL>

### ISSUE THREAD

**Issue by CabuxaMapache** [danishkhan/NicEdit#9]
When the textarea is inside a "ul", the unordered list button is selected at editor's load. That's incorrect and take to confusion.
I've solved it in my project doing this in "nicEditorButton.checkNodes" function:

// Before
//if (this.options.tags && bkLib.inArray(this.options.tags, elm.nodeName)) {

// After
if (this.options.tags && bkLib.inArray(this.options.tags, elm.nodeName) && elm.className.indexOf('myULClass') == -1) {

**Comment by danishkhan** [comment]
This project isn't maintained anymore. If you'd like to add a fix a PR is welcome otherwise you might want to fork it or look for another editor.
